### PR TITLE
Limitation: Document docker --security-opt option not supported

### PR DESCRIPTION
**Pull request by nitkon**
Fixes: #241

Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks @nitkon!

lgtm

**Comment by jcvenegas** [comment]
lgtm

**Comment by jcvenegas** [comment]
ping @kata-containers/documentation

**Comment by caoruidong** [comment]
lgtm.
Is this to say we don't support all --security-opt like apparmor as well?

**Comment by nitkon** [comment]
@jcvenegas @jodh-intel : Updated my PR.

**Comment by jodh-intel** [comment]
lgtm.

@klynnrif - ptal.

**Comment by gnawux** [comment]
looks good, and it is not a big patch.

let's merge it.

**Pull request merged**
