### PR TITLE
docs: Add validation section for kata manager

### PR DESCRIPTION
**Pull request by didier-durand**
docs: Add validation section for kata manager

Add a new section to the `kata-manager` installation guide to help users validate their installations.

Fixes: #750.

Signed-off-by: didier <durand.didier@gmail.com>

### CODE REVIEW

**Comment by didier-durand** [comment]
This is a new version of PR #747 based on guidance

**Review by jodh-intel — COMMENTED** [review]
Thanks @didier-durand. There are a couple of small issues that need to be resolved (very quick to do ;) and one optional one. We are almost there I think :smile:

- Your sign-off is failing our automated check:
  ```
  - Error: The SoB (DCO) check failed

  5e6f7267f43169c3556352151d81fae09e02483f    Expected "Didier Durand 
  <durand.didier@gmail.com>", but got "didier <durand.didier@gmail.com>".
  ```

- The body of the commit needs folding as it is too long:

  ```
  ERROR: commit 5e6f7267f43169c3556352151d81fae09e02483f: body line 3 too long (max 72, got 103): "Add a new section to the `kata-manager` installation guide to help users validate their installations.\r"
  ```

- Finally (optional): The title line in the commit (`docs: Add validation section for kata manager`) is duplicated fwics.

As mentioned, you do not need to raise a new PR (we'd rather you didn't) - just `git rebase -i master && git push -f` to update the existing PR.

Thanks very much!

**Review by cmaf — CHANGES_REQUESTED** [review]
@didier-durand lgtm, approval pending changes to the commit message described above

**Comment by didier-durand** [comment]
Guys, I am puzzled by the DCO check having an issue with my sign-off:

5e6f7267f43169c3556352151d81fae09e02483f    Expected "Didier Durand <durand.didier@gmail.com>", but got "didier <durand.didier@gmail.com>".
  fff15e198b4f5929e9e5841a15ff0a50b9e803f6    Expected "didier <durand.didier@gmail.com>", but got "Didier Durand <durand.didier@gmail.com>".

What can I do to fix?

Sorry for the noise!

Didier

**Comment by jodh-intel** [comment]
Hi @didier-durand - I've never seen this before but the failure is coming from @Tim-Zhang's GitHub dco action here:

- https://github.com/tim-actions/dco/blob/master/libs/dco.js#L54

Firstly, I'd squash all your commits into a single one so there is only a single Signed-off-By to worry about. Secondly, check that the email address you are specifying in the Signed-off-by matches the email address specified in the commit itself, *and* that the email address matches your *primary* GitHub email address.

/cc @Tim-Zhang

**Comment by didier-durand** [comment]
Guys, I can't get rid of the sign-off issue (tried to squash commits bit it didn't solve) : I changed my user from didier to Didier Durand and now, even I revert back to didier,  the DCO check complains. Should I close this one ? Let me know if you do the change in doc on your own of if you want me to re-open it.

**Pull request closed without merging**
