### PR TITLE
Update install README.md

### PR DESCRIPTION
**Pull request by it2911**
Fixup the OpenSuse link mistake

### CODE REVIEW

**Comment by devimc** [comment]
@it2911 thanks for the pull request, but you need to fix your commit message, please take a look to this example https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Comment by devimc** [comment]
or this example https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

**Comment by devimc** [comment]
Hi @it2911  any update ?

**Comment by caoruidong** [comment]
Ping @it2911

**Comment by caoruidong** [comment]
This is fixed by https://github.com/kata-containers/documentation/pull/229. We can close it.

**Comment by jodh-intel** [comment]
Closing...

**Pull request closed without merging**
