### PR TITLE
version: Create a VERSION file

### LINKED ISSUE #246: stable: consider forking documentation repository
see https://github.com/kata-containers/documentation/pull/238#discussion_r216558185

### PR DESCRIPTION
**Pull request by amshinde**
Since we want to start tagging and branching this repo,
create a VERSION file starting with the last version released.

Fixes #246

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@jcvenegas @chavafg PTAL.
Once this is merged, I will tag this as 1.11.0-alpha1. This should be sufficient for https://github.com/kata-containers/packaging/pull/1008 to pass I think.

**Comment by jcvenegas** [comment]
@amshinde @jodh-intel @chavafg because in the past we did not branched stable branches and still may be need this for old branches releases I created `stable-1.9` and `stable-1.10` using tip on master, we will want to add a VERSION file  for other branches to help our release scripts have an env as they expect.

**Comment by amshinde** [comment]
@jcvenegas Thanks. I'll create the VERSION files for the stable branches.

**Pull request merged**
