### PR TITLE
docs: Add documents to architecture.md to illustrate kata agent's int…

### LINKED ISSUE #560: Add documentation to architecture.md to illustrate kata-agent's internal

### PR DESCRIPTION
**Pull request by jjhegg**
…ernal

illustrate kata agent's internal, help people to understand it.

Fixes #560

Signed-off-by: jjhegg <wangyanjia@inspur.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks @jjhegg - great diagram! However, please can you add the "source" for the diagram to this PR too. Ideally, that file would be usable by open source tooling to allow anyone to update it further (so SVG would be great if possible)?

**Comment by jodh-intel** [comment]
@jjhegg - please could you add the diagram sources so we can get this merged?

**Comment by jodh-intel** [comment]
Ping @jjhegg.

**Comment by egernst** [comment]
Its a nice drawing.  We should look at leveraging this. Anyone want to redraw and include sources?

**Comment by c3d** [comment]
Sent a mail ping @jjhegg since it's not clear he received a notification.

**Review by c3d — CHANGES_REQUESTED** [review]
In addition to getting the source for the diagram, I would also like if possible to make the background of the kata-agent box to be a single color for clarity.

**Comment by fidencio** [comment]
Folks, this PR has been stale and I'm closing it as we're walking towards the **final** 1.13.0 release of the kata-containers-1.x.
From now on, all the development will happen as part of https://github.com/kata-containers/kata-containers/ and fixes should be provided to that repo.

Thanks a lot for your contribution, we're sorry that for some reason it got stale, and we hope to see you around for new adventures in the kata-containers-2.x land.

**Pull request closed without merging**
