### PR TITLE
docs: Fix typo

### PR DESCRIPTION
**Pull request by qzivli**
Fix typo: librdbd1 -> librbd1 in install/debian-installation-guide.md

### CODE REVIEW

**Comment by nitkon** [comment]
Thanks for raising a PR @qzivli . Could you please follow the patch format as mentioned here in the [docs](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format)

**Comment by grahamwhaley** [comment]
Hi @qzivli - change looks good to me - nice find.
The CI is moaning as you'll need to make a couple of modifications to your commit to meet our submission requirements:

- you need some subject body (currently empty)
- you need to 'sign off' the commit.

You can do this with a `git commit --amend` followed by a `git push -f <my repo> <my branch>` I think - you don't need to re-open the PR or add any extra commits etc. :-)

Details can be found at https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

The CI message is:

```
Found 1 commit between commit 3ba442cdbd45084a5e0e218c32f90061028e29e8 and branch master
ERROR: Commit 3ba442cdbd45084a5e0e218c32f90061028e29e8: pure whitespace body
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

**Comment by amshinde** [comment]
@qzivli lgtm with the changes @grahamwhaley suggested.

**Comment by jodh-intel** [comment]
Thanks @qzivli !

lgtm

**Pull request merged**
