### PR TITLE
install: Improve snap documentation

### LINKED ISSUE #766: How to install Kata Containers via Snap on Ubuntu
see https://github.com/kata-containers/kata-containers/issues/1138

### PR DESCRIPTION
**Pull request by devimc**
Improve snap documentation, document how to install
kata 1.x and 2.x, how to configure them and their integration
with container engines.

fixes #766

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
cc @dev-rke

**Comment by devimc** [comment]
cc @didier-durand

**Comment by didier-durand** [comment]
@devimc : Thanks for this info! 
Will the additional info provided in this PR regarding podman confi file solve my ticket https://github.com/kata-containers/kata-containers/issues/1152 ?
Didier

**Comment by devimc** [comment]
@didier-durand I don't think so, podman and docker don't support kata 2.x (and I don't know when they will support it), I've updated the document to emphasize this.

**Comment by dev-rke** [comment]
Hi @devimc , 

Thanks, i'd recommend to add the exact command `$ sudo systemctl restart docker` to simplify installation for beginners.
Rest of the pull request looks good to me.

**Review by GabyCT — APPROVED** [review]

**Review by chavafg — APPROVED** [review]

**Pull request merged**
