### PR TITLE
Add Debian 10

### PR DESCRIPTION
**Pull request by mnaser**
It seems like we're building packages for Debian 10 right now anyways.

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/me notes, presuming this is fine, we'll need a SoB and 'Fixes' in the commit to pass the CI:
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

I know, all that process for an extra 4 chars... but, that is our flow/CI..

**Comment by jodh-intel** [comment]
Ref: https://github.com/kata-containers/packaging/issues/647.

**Comment by egernst** [comment]
@mnaser looks good -- just need the commit updates graham mentioned

**Comment by jodh-intel** [comment]
We need this landed so I've created #585 to replace this.

**Pull request closed without merging**
