### PR TITLE
Update installation information

### PR DESCRIPTION
**Pull request by fidencio**
This PR aims to update the installation information for the distros claimed to be supported.

The main changes here are:
- CentOS:  use packages from the virtualization special interest group;
- Fedora: use the packages provided by the distro;
- openSUSE: use the packages provided by the distro;
- RHEL: drop the information;
- SLES: use the packages provided by the distro;

I still have to check what's the state of the packages on Ubuntu and Debian, once it's done I can remove the "WIP:" tag.

### CODE REVIEW

**Comment by fidencio** [comment]
@rhafer, may I ask for an input to double-check the instructions of the following pages?
- https://github.com/fidencio/kata-documentation/blob/wip/update-install-information/install/sle-15sp1-installation-guide.md
- https://github.com/fidencio/kata-documentation/blob/wip/update-install-information/install/opensuse-leap-15.1-installation-guide.md
- https://github.com/fidencio/kata-documentation/blob/wip/update-install-information/install/opensuse-installation-guide.md

From the tests I've made, Leap 15.2+ and Tumbleweed have the packages as part of the distro. Leap 15.1 doesn't, but it'll reach its EOL soon enough that we can add a page now and remove it in November.

About the Enteprise, SLE 15 SP1 follows Leap 15.1 and doesn't have the packages there. But what about 15.2? Am I safe to assume that it already has `katacontainers` as part of the distro? If so, I'll need to update it.

**Review by jodh-intel — APPROVED** [review]
Nice! Thanks @fidencio.

lgtm

Notes:

- We need to ensure https://github.com/kata-containers/ci/issues/318 is fixed before we land this ideally (so adding `do-not-merge` for now...).
- Once this is merged, would you be able to port to 2.0? I've raised https://github.com/kata-containers/kata-containers/issues/623 so we don't forget :smile:

**Comment by rhafer** [comment]
> From the tests I've made, Leap 15.2+ and Tumbleweed have the packages as part of the distro. Leap 15.1 doesn't, but it'll reach its EOL soon enough that we can add a page now and remove it in November.

:+1:

> About the Enteprise, SLE 15 SP1 follows Leap 15.1 and doesn't have the packages there. But what about 15.2? Am I safe to assume that it already has `katacontainers` as part of the distro? If so, I'll need to update it.

Even though many packages are shared between Leap and SLE there are some differences in which packages are included. So currently kata is not directly part of SLE 15 SP2 and the install instructions would be the same as for SP1. However, I just noticed that the SP2 repos on `devel:kubic` haven't been enabled yet. (I'll try to get that fixed)

Other than that the changes look good to me.

**Comment by fidencio** [comment]
>     * Once this is merged, would you be able to port to 2.0? I've raised [kata-containers/kata-containers#623](https://github.com/kata-containers/kata-containers/issues/623) so we don't forget smile

Sure thing. It won't be a direct backport tho, as for 2.0 we'll stop building the community packages entirely.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
