### PR TITLE
GCE tweaks

### LINKED ISSUE #173: GCE doc tweaks
Add GCE install guide to main install readme and add a toc to the GCE doc.

### PR DESCRIPTION
**Pull request by jodh-intel**
Add the new Google Compute Engine installation guide to the installation README.

Also,

- Add a table of contents to the Google Compute Engine install guide.
- Simplify the installation README by using relative URLs - let github expand them automatically for readers.

Fixes #173.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/me sees pullapprove complaining about a SOB

**Comment by grahamwhaley** [comment]
16.04 CI has suffered 'not a TTY' death

**Comment by jodh-intel** [comment]
No idea why github is complaining about that commit because it **does** have the required SOB - pullapprove has checked it and is happy with it...

**Comment by chavafg** [comment]
should we remove the `-ti` option from the guides

**Comment by jodh-intel** [comment]
... on issue https://github.com/kata-containers/documentation/issues/175.

**Comment by jodh-intel** [comment]
PR https://github.com/kata-containers/documentation/pull/176 raised.

**Comment by jodh-intel** [comment]
Hi @egernst - I think this PR is one we can avoid sending for a full doc review as it's 99.9% adding/changing URLs. Could you review when you get a sec?

**Comment by jodh-intel** [comment]
This doc has been approved and the changes are basically structural.

Two weeks is too long to keep doc PRs open so merging....

**Pull request merged**
