### PR TITLE
docs: Update directory and change kata_tap0 to tap0_kata

### PR DESCRIPTION
**Pull request by frostmourner**
Update directory about state and tap device's should be tap0_kata for architecture.md

Signed-off-by: duanquanfeng <duanquanfeng_yewu@cmss.chinamobile.com>

### CODE REVIEW

**Comment by devimc** [comment]
thanks @frostmourner - please file an issue and add "fixes #NNNN" in you commit message, for more information read https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

**Comment by cmaf** [comment]
@frostmourner, could you file an issue to link to this PR?

**Review by amshinde — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @frostmourner. Please could you update the commit as mentioned so we can land this?

Also, it would be great if you could port this to Kata 2.0 (https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs).

**Comment by cmaf** [comment]
Forward port is https://github.com/kata-containers/kata-containers/pull/798

**Pull request merged**
