### PR TITLE
Minor fix in minikube-installation-guide.md with invalid path

### PR DESCRIPTION
**Pull request by markkuleppala**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks for raising! However, we require that PRs are formatted in a particular way.

Please take a look at our [contributing guide](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) which explains what you have to do to make the PR "well formed", which will allow the CI's to pass (some are currently failing if you look at the bottom of the PR).

Also, please can you explain your changes. I see a comment in the commit, but it is very brief and doesn't actually explain *why* this change is required.

**Comment by egernst** [comment]
This change is legit -  just need to reformat commit, if you're willing @markkuleppala  

Thanks for the heads up -- if you don't get to it - I'm happy to pick submit a PR.

**Comment by fidencio** [comment]
> This change is legit - just need to reformat commit, if you're willing @markkuleppala
> 
> Thanks for the heads up -- if you don't get to it - I'm happy to pick submit a PR.

@egernst, please, would you mind picking this one up and submitting a PR? :-)

**Comment by fidencio** [comment]
Wait, hold-on, I'll pick up legit issues and submit one mega PR.

**Comment by fidencio** [comment]
This was superseded by https://github.com/kata-containers/documentation/pull/789

**Pull request closed without merging**
