### PR TITLE
docs: fix a link in installing-with-kata-manager.md

### PR DESCRIPTION
**Pull request by yangy2000**
Fix the link from #install-kata-packages-only to #install-the-kata-packages-only

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Thanks @yangy2000 - the change looks good to me :-). I think we need to clean up the submission a little though before we land it.
The PR is showing 6 commits, where I expect we only need one. You might want to use `git rebase -i HEAD~6` or similar to squash those commits down into one and/or drop ones you don't really need etc.

The CI is also noting that some of the patches do not conform to our required format - I suspect those patches are going to be dropped/squashed anyway, and it looks like your last patch and submission are fairly good. I'll post the info/link anyway - as I'm not sure you have the required 'Fixes' item in any of the commits.

```
Found 2 commits between commit cb67aec406dbf67a9764b2b4212a57617db1e484 and branch master
ERROR: Commit d3d9776775d6151190286c67727fc3aaa767589e: Failed to find subsystem in subject: "fix a link in installing-with-kata-manager.md"
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

If you need any more input on cleaning up the patchset, please do ask.

**Comment by jodh-intel** [comment]
Hi @yangy2000 - thanks for squashing the commits. Travis is still complaining because your commit doesn't reference a github issue. I've just raised #295 for you so all you need to do is add a `Fixes #295` comment in your commit and re-push:

```
docs: fix a link in installing-with-kata-manager.md

Fix the link from #install-kata-packages-only to #install-the-kata-packages-only

Fixes #295.

Signed-off-by: Alex Yang <yangyang1@zte.com.cn>
```

Once done...

lgtm

**Comment by sboeuf** [comment]
@yangy2000 please fix the commit message, otherwise we won't be able to merge this PR.

**Comment by raravena80** [comment]
@yangy2000 ping (from your weekly Kata herder)

**Comment by jodh-intel** [comment]
Merging...

**Pull request merged**
