### PR TITLE
docs: add param to sandbox design api

### PR DESCRIPTION
**Pull request by YchauWang**
Add param to sandbox design apis doc. Update kata-api-design.md file,
the apis for the sandbox operations.
link to: https://github.com/kata-containers/documentation/issues/727

Fixes: #729

Signed-off-by: Ychau Wang <wangyongchao.bj@inspur.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @YchauWang.

**Review by cmaf — APPROVED** [review]
lgtm @YchauWang

**Comment by cmaf** [comment]
@YchauWang, is this meant to be a backport of [#702](https://github.com/kata-containers/kata-containers/pull/702)? I noticed some differences between 2.x and 1.x, such as the Sandbox Management API table ([2.x](https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/design/kata-api-design.md#sandbox-management-api), [1.x](https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md#sandbox-management-api)).

**Review by cmaf — CHANGES_REQUESTED** [review]
Sorry @YchauWang noticed one thing with a possible forward port, see above comment.

**Comment by YchauWang** [comment]
> @YchauWang, is this meant to be a backport of [#702](https://github.com/kata-containers/kata-containers/pull/702)? I noticed some differences between 2.x and 1.x, such as the Sandbox Management API table ([2.x](https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/design/kata-api-design.md#sandbox-management-api), [1.x](https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md#sandbox-management-api)).

@cmaf , this is 1.x sandbox api, it is differences between 2.x and 1.x, including the parameter name. Try to fix c3d's bug #729, I just add the api parameters by the 1.x runtime project codes.

**Comment by YchauWang** [comment]
And Please help add [no-forward-port-needed] and [no-backport-needed] labels, thank you very much.

**Comment by jodh-intel** [comment]
@YchauWang - please can you respond to @cmaf's comments (https://github.com/kata-containers/documentation/pull/745#issuecomment-708860606)

**Comment by YchauWang** [comment]
> can you respond to

Sorry, I didn't understand @cmaf 's comments, the first time. I will sync the api description of the sandbox's apis now from 2.x. sorry for my mistake.

**Review by cmaf — APPROVED** [review]

**Pull request merged**
