### PR TITLE
limitations: remove 'docker run and kernel memory' section

### LINKED ISSUE #239: update limitations
issue https://github.com/kata-containers/runtime/issues/187 was fixed, hence documentation must be updated

### PR DESCRIPTION
**Pull request by devimc**
issue https://github.com/kata-containers/runtime/issues/187 was fixed

fixes #239

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
\o/

lgtm

**Comment by jcvenegas** [comment]
lgtm

**Comment by jcvenegas** [comment]
@kata-containers/documentation  ping

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
