### PR TITLE
docs: Use kernel build script for building kernel in developer guide

### PR DESCRIPTION
**Pull request by nitkon**
Use 4.19.x config file when building kernel. 

Fixes: #507

Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Agree. I already asked/suggested we do that pretty recently when somebody else PRd the same or similar change I think - we already have the kernel build docs and script over at https://github.com/kata-containers/packaging/tree/master/kernel including documentation. Can you ammend this PR to point to those instructions instead please @nitkon , then we won't have to play catchup here every time we make a kernel version change.

**Comment by nitkon** [comment]
@jodh-intel @grahamwhaley : PTAL ...

**Comment by nitkon** [comment]
@grahamwhaley : Done. 👍

**Comment by eadamsintel** [comment]
I just tried build-kernel.sh on Clear Linux and it complained that the arch command was missing which happened previously with OSbuilder. This should be easily replaceable with a uname command instead.

`
go/src/github.com/kata-containers/tests/.ci/lib.sh: line 38: arch: command not found
`

It seemed to build the kernel OK and I was able to boot up a kata container with that kernel.

**Pull request merged**
