### PR TITLE
modify the error url of logfmt

### PR DESCRIPTION
**Pull request by CriaHu**
docs: modify the error url of logfmt

There are many error urls, which will affect the correctness of the document. I changed the error url to the correct url.

Fixes: https://github.com/kata-containers/documentation/issues/740

Signed-off-by: Cria Hu  <huyuqing@inspur.com>

### CODE REVIEW

**Comment by CriaHu** [comment]
issue: 
https://github.com/kata-containers/documentation/issues/740

**Review by jodh-intel — APPROVED** [review]
Thanks @CriaHu.

lgtm

**Comment by jodh-intel** [comment]
@CriaHu - Note that Travis is failing as you'll need to modify the format of the commit to match the format shown here:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Review by lifupan — APPROVED** [review]

**Comment by cmaf** [comment]
Hi @CriaHu, could you please modify the format of the commit based on [this comment](https://github.com/kata-containers/documentation/pull/746#issuecomment-707735432)?

**Comment by CriaHu** [comment]
ok, @cmaf

**Pull request merged**
