### PR TITLE
architecture.md: add network hotplug diagram

### PR DESCRIPTION
**Pull request by bergwolf**
To document the design we have agreed on network hotplug support.

Fixes: #220

cc @WeiZhang555 @caoruidong

### CODE REVIEW

**Comment by bergwolf** [comment]
@egernst I thought about it as well but I'm not sure about where to put it. It feels a bit overwhelming to include the source text in architecture.md. Do you have any suggestions?

**Comment by caoruidong** [comment]
Update this doc https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md ?

**Comment by bergwolf** [comment]
@caoruidong yeah, that one also needs updating. Fixed. Thanks!

**Comment by jodh-intel** [comment]
Hi @bergwolf - please can you add the plantuml source for the diagram as `arch-images/kata-containers-network-hotplug.txt`. In other words, the text file that starts with:

```
@startuml

    :

@enduml
```

That way, anyone can paste that file into https://www.planttext.com/ to modify the png file.

**Comment by bergwolf** [comment]
@jodh-intel Ah, thanks! I didn't know all other images have their txt source put under `arch-image` directory. I've added the one for network hotplug. PTAL.

**Comment by jodh-intel** [comment]
Nice - thanks @bergwolf!

lgtm

**Comment by grahamwhaley** [comment]
and thx @bergwolf - please ignore my other comment on the other thread :-)

**Comment by caoruidong** [comment]
Thanks lgtm

**Comment by devimc** [comment]
@bergwolf if possible please add the license header

```
ERROR: Required license identifier ('SPDX-License-Identifier: Apache-2.0') missing from following files:

arch-images/kata-containers-network-hotplug-uml.txt
```

**Comment by devimc** [comment]
@bergwolf any update on this?

**Comment by bergwolf** [comment]
@devimc All the other *.txt files in the same directory do not contain a license header, and it helps since people can simply copy and paste them to generate new images. Do we require license headers to be present in all of them?

**Comment by jodh-intel** [comment]
It looks like the other files managed to avoid needing a license header since we only added the CI scripts to this repo *after* they had been added (and https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L314 only looks for changed files to complain about missing headers in).

So, we either add the header as a comment to this file (quick to do), or raise a new PR to add a new license header exclusion (which is probably going to take a little longer ;):

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L334..L347

**Comment by grahamwhaley** [comment]
@jodh-intel @bergwolf - did we decide which route to take to get past the SPDX header check here - will we add it to the file, or will we make an exception for image files?

**Comment by jodh-intel** [comment]
idm - If the image format is text-based and supports comments, I think it's safer if we add the copyright. But users are also free to raise a PR on the static check scripts if they disagree ;)

**Comment by jodh-intel** [comment]
Hi @bergwolf - could you rebase this PR? I've just raised https://github.com/kata-containers/tests/pull/770 so you won't need to add licence headers to the text file (but you do owe me a :beer: :laughing:)

**Comment by jodh-intel** [comment]
Hahaa! Can't wait! ;)

**Pull request merged**
