### PR TITLE
install: minikube: add containerd details

### PR DESCRIPTION
**Pull request by grahamwhaley**
We only documented how to launch minikube/kata with CRI-O. It is
trivial to flip this to containerd, and that also works with kata-deploy,
so document it.

Fixes: #660

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
ouch! CI isn't happy

```
ERROR: found HTTP error status codes for URL https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver

ERROR: Invalid URL 'https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver' found in the following files:
```

**Comment by grahamwhaley** [comment]
> ouch! CI isn't happy
> 
> ```
> ERROR: found HTTP error status codes for URL https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver
> 
> ERROR: Invalid URL 'https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver' found in the following files:
> ```

Ooh, that looks like potential external rot - let me go check... thx!

**Comment by grahamwhaley** [comment]
Found it I think - let me update the PR... https://minikube.sigs.k8s.io/docs/drivers/kvm2/

**Comment by grahamwhaley** [comment]
URL updated - try again
/test-ubuntu

**Comment by devimc** [comment]
thanks @grahamwhaley

**Pull request merged**
