### PR TITLE
zun: update kata install instructions

### PR DESCRIPTION
**Pull request by marcov**
Update zun guide to point to the kata installation instructions for
Ubuntu.

Fixes: #371

Signed-off-by: Marco Vedovati <mvedovati@suse.com>

### CODE REVIEW

**Comment by marcov** [comment]
Mmmh, now I have the doubt that the installation instructions **needs** to be hardcoded to be machine parsed. In this case I can update the PR.

/cc @jodh-intel @grahamwhaley

**Comment by grahamwhaley** [comment]
@marcov - I'm not sure I follow. the PR here looks good, which drops the hand coding of `$(lsb_release -rs)` for instance, and moves the onus over to the ubuntu install dirs. Or, are you saying you could just say 'install per the OS of your choice', and not even explicitly mention Ubuntu? Which, would also work for me.

**Comment by marcov** [comment]
@grahamwhaley I was wondering if this page could parsed by something similar to kata-doc-to-script to generate some install script. In that case a link wouldn't work.

**Comment by jodh-intel** [comment]
@marcov - we could do that, but we'd probably need to put the logic into https://github.com/kata-containers/tests/blob/master/cmd/kata-manager/kata-manager.sh itself (as we do for the docker install atm).

lgtm

**Comment by jcvenegas** [comment]
ping, this need rebase master.

**Comment by grahamwhaley** [comment]
:-) I think I'm going to go disable all those 'branch is out of date' warnings from github, as most of the time I think they are still mergeable - and github gives us a different (and more blatant) warning if they are not mergeable..

**Comment by marcov** [comment]
Rebased

/test

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
